# -*- coding: utf-8 -*-
"""face mask detection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/abdallahmahmoudkamel/face-mask-detection.98ef759f-d334-4322-b356-6c81a8b395f2.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260627/auto/storage/goog4_request%26X-Goog-Date%3D20260627T170811Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D668d64288263247dbc69657aadfadb8397314af87656f697bdd2939e4ae65d86f88b4d932a9ed6c0f519255f9bc14945fefc7a4ec7da6ec1a93a4a4fe838d3af8bcad52c43786d78a55104c9413d9d5ee05b11acd04e26b506bf1859e954c69c57779754af40a047735e1421e95bf040c576a56f458d517ebc2676da5cac2d545cde2b1b84f9974bbf02d630b5d876042850e553456d542f67b302e94d7c8100066680bed585403bd540c6e5d7ded1ff6227966c921d7ef5e93e0b5eb909ae7c66c44fdd35b338b30c0af96176a3ac97ac08973497144a2f0a96a9e9c7e2306db52253753f8008ad7a2d34c01b671be33de426e95177bb59e6b13e277d055b5e

# **Import Significant Libraries**
"""

import os
import pandas as pd
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import EfficientNetB3
import numpy as np
from tensorflow.keras.layers import Dense,Flatten , Dropout
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import classification_report,confusion_matrix
import seaborn as sns

"""# Function to create dataset includes paths and its labels"""

def create_data_set(path):
    images = []
    labels = []
    folders = os.listdir(path)
    for folder in folders:
        folder_path = os.path.join(path , folder)
        files = os.listdir(folder_path)
        for file in files:
            file_path = os.path.join(folder_path , file)
            images.append(file_path)
            labels.append(folder)
    data = pd.DataFrame({"file_paths" : images , "labels":labels})
    return data

data = create_data_set("/kaggle/input/face-mask-dataset/data")
data

"""# splitting the data into"""

train , dummy = train_test_split(data , test_size = 0.3 , random_state = 44 , stratify = data["labels"])

valid , test = train_test_split(dummy , test_size = 0.5 , random_state = 44 , stratify = dummy["labels"])

class_counts = train["labels"].value_counts()
class_counts

"""# some visulaization for the data"""

plt.figure(figsize=(10, 6))
plt.bar(class_counts.index, class_counts.values, color='skyblue')
plt.xlabel('Class')
plt.ylabel('Frequency')
plt.title('Class Distribution')
plt.xticks(rotation=45)
plt.show()

plt.pie(class_counts.values , labels = class_counts.index , autopct = "%1.2f%%",explode = [0.1 , 0.1])

"""# effects that will be applied in training using data augmentation methodolgy"""

train_gen = ImageDataGenerator(
    rescale=1./255,           # Normalize pixel values
    rotation_range=10,        # Small rotations
    width_shift_range=0.1,    # Horizontal shift
    height_shift_range=0.1,   # Vertical shift
    zoom_range=0.1,           # Slight zoom in/out
    brightness_range=[0.8, 1.2],  # Adjust brightness
    horizontal_flip=True,     # Flip images horizontally
    fill_mode='nearest'       # Fill missing pixels
)

test_gen = ImageDataGenerator(rescale = 1./255)

"""**applying augmentation for the data**"""

training_data = train_gen.flow_from_dataframe(train,x_col = "file_paths" , y_col = "labels" , target_size = (256 , 256) , color_mode = "rgb" , class_mode = "categorical" , batch_size = 16 , shuffle = True)

validation_data = test_gen.flow_from_dataframe(valid,x_col = "file_paths" , y_col = "labels" , target_size = (256 , 256) , color_mode = "rgb" , class_mode = "categorical" , batch_size = 16 , shuffle = False)

testing_data  = test_gen.flow_from_dataframe(test,x_col = "file_paths" , y_col = "labels" , target_size = (256 , 256) , color_mode = "rgb" , class_mode = "categorical" , batch_size = 16 , shuffle = False)

"""# visualize a subset from the data #"""

images, labels = next(training_data)
class_indices = np.argmax(labels, axis=1)

class_names = list(training_data.class_indices.keys())

batch_size = 16
plt.figure(figsize=(15, 10))
for i in range(min(batch_size, 16)):
    plt.subplot(4, 4, i + 1)
    plt.imshow(images[i])
    plt.title(f"Class: {class_names[class_indices[i]]}")
    plt.axis('off')
plt.tight_layout()
plt.show()

"""# creating the base model for extraction the features"""

base_model = EfficientNetB3(weights = "imagenet" , include_top=False,input_shape = (256 , 256 , 3) , pooling = "max")
base_model.trainable = True

"""# build the structure of the network"""

model = Sequential([
    base_model,
    Flatten(),
    Dense(128 , activation = "relu"),
    Dropout(0.3),
    Dense(64 , activation = "relu"),
    Dense(train["labels"].nunique() , activation = "softmax")
])

model.summary()

optimizer = Adam(learning_rate = 0.001)

model.compile(optimizer , loss = "categorical_crossentropy" , metrics = ["accuracy"])

early_stopping = EarlyStopping(monitor = "val_accuracy" , patience = 3 , restore_best_weights = True)

"""# training the model"""

history = model.fit(training_data , batch_size = 16, validation_data = validation_data , epochs = 20 , callbacks = [early_stopping])

"""# evaluating the model"""

testing_loss,testing_accuracy = model.evaluate(testing_data)
validation_loss , validation_accuracy = model.evaluate(validation_data)

print(f"testing_loss is {testing_loss}")
print(f"testing_accuracy is {testing_accuracy}")

print("--------------------------------------")

print(f"validation_loss is {validation_loss}")
print(f"validation_accuracy is {validation_accuracy} ")

"""# drawing the accuracy and loss plots for training and validation"""

plt.plot(history.history["accuracy"])
plt.plot(history.history["val_accuracy"])

plt.title("Model Accuracy")
plt.xlabel("epoch")
plt.ylabel("accuracy")
plt.legend(["training" , "validation"] , loc = "lower right")
plt.show()

plt.plot(history.history["loss"])
plt.plot(history.history["val_loss"])

plt.title("Model Loss")
plt.xlabel("epoch")
plt.ylabel("loss")
plt.legend(["training" , "validation"] , loc = "lower right")
plt.show()

testing_labels = model.predict(testing_data)
predictions = np.argmax(testing_labels , axis = 1)

print(classification_report(testing_data.classes , predictions))

cm = confusion_matrix(testing_data.classes , predictions)
print(cm)

plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=class_names, yticklabels=class_names)

plt.xlabel("prediction")
plt.ylabel("actual")
plt.title("confusion matrix HeatMap")
plt.show()

"""# saving the structure and the parameters of the model"""

Model = model.save("face_mask.h5")